package com.foxor.jcard.geml.expressions;

import com.foxor.jcard.geml.Expression;
import com.foxor.jcard.geml.Machine;

/**
 * 
 * The client adds an InitializationVector rule to the beginning of the rules before sending them,
 * so that any randomly generated actions have a source to draw from
 * 
 * Used to set up the RNG on the server, generated by client automatically
 * 
 * @author ijames1
 *
 */
public class InitializationVector extends Expression {
    
    /**
     * The measured millisecond on the client machine when this message was generated
     */
    protected int ms;

    public int getMs() {
        return ms;
    }

    public void setMs(int ms) {
        this.ms = ms;
    }

    @Override
    public Expression execute(Machine m) throws Exception {
        m.addRandomness(ms);
        return this;
    }
}